//  @ts-check

import { tanstackConfig } from '@tanstack/eslint-config'

export default [
  ...tanstackConfig,
  {
    rules: {
      'import/no-cycle': 'off',
      'import/order': 'off',
      'sort-imports': 'off',
      '@typescript-eslint/array-type': 'off',
      '@typescript-eslint/require-await': 'off',
      'pnpm/json-enforce-catalog': 'off',
    },
  },
  {
    ignores: [
      'eslint.config.js',
      'prettier.config.js',
      // Generated by `convex dev` — rewritten on every schema change.
      'convex/_generated/**',
      // The Claude Design canvas export: a design reference, not app source.
      // support.js there is a generated canvas runtime marked "do not edit".
      '2nd version Daily focus with chain model/**',
      // Third-party skill packages, installed via `skills add`.
      '.claude/**',
      '.agents/**',
      '.wrangler/**',
      '.output/**',
      'dist/**',
    ],
  },
]
