//  @ts-check

import { tanstackConfig } from '@tanstack/eslint-config'

export default [
  ...tanstackConfig,
  {
    rules: {
      'import/no-cycle': 'off',
      'import/order': 'off',
      'sort-imports': 'off',
      '@typescript-eslint/array-type': 'off',
      '@typescript-eslint/require-await': 'off',
      'pnpm/json-enforce-catalog': 'off',
      /* Convex's useQuery drops its subscription on unmount, which made every
         page switch flash a skeleton. The cached hook keeps it (see
         src/integrations/convex/provider.tsx). */
      'no-restricted-imports': [
        'error',
        {
          paths: [
            {
              name: 'convex/react',
              importNames: ['useQuery'],
              message:
                "Import useQuery from 'convex-helpers/react/cache/hooks' so the subscription survives a page switch.",
            },
          ],
        },
      ],
    },
  },
  {
    ignores: [
      'eslint.config.js',
      'prettier.config.js',
      // Generated by `convex dev` — rewritten on every schema change.
      'convex/_generated/**',
      // The Claude Design canvas export: a design reference, not app source.
      // support.js there is a generated canvas runtime marked "do not edit".
      'design/**',
      // Third-party skill packages, installed via `skills add`.
      '.claude/**',
      '.agents/**',
      '.wrangler/**',
      '.output/**',
      'dist/**',
    ],
  },
]
