/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppSplatRouteImport } from './routes/_app/$'
import { Route as AppBacklogRouteImport } from './routes/_app/backlog'
import { Route as AppBodyRouteImport } from './routes/_app/body'
import { Route as AppCalendarRouteImport } from './routes/_app/calendar'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppFinancesRouteImport } from './routes/_app/finances'
import { Route as AppGoalsRouteImport } from './routes/_app/goals'
import { Route as AppLanguagesRouteImport } from './routes/_app/languages'
import { Route as AppReviewsRouteImport } from './routes/_app/reviews'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppNotesIndexRouteImport } from './routes/_app/notes.index'
import { Route as AppNotesIdRouteImport } from './routes/_app/notes.$id'
import { Route as AppProjectsIndexRouteImport } from './routes/_app/projects.index'
import { Route as AppProjectsIdRouteImport } from './routes/_app/projects.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSplatRoute = AppSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AppRoute,
} as any)
const AppBacklogRoute = AppBacklogRouteImport.update({
  id: '/backlog',
  path: '/backlog',
  getParentRoute: () => AppRoute,
} as any)
const AppBodyRoute = AppBodyRouteImport.update({
  id: '/body',
  path: '/body',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppFinancesRoute = AppFinancesRouteImport.update({
  id: '/finances',
  path: '/finances',
  getParentRoute: () => AppRoute,
} as any)
const AppGoalsRoute = AppGoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => AppRoute,
} as any)
const AppLanguagesRoute = AppLanguagesRouteImport.update({
  id: '/languages',
  path: '/languages',
  getParentRoute: () => AppRoute,
} as any)
const AppReviewsRoute = AppReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppNotesIndexRoute = AppNotesIndexRouteImport.update({
  id: '/notes/',
  path: '/notes/',
  getParentRoute: () => AppRoute,
} as any)
const AppNotesIdRoute = AppNotesIdRouteImport.update({
  id: '/notes/$id',
  path: '/notes/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsIndexRoute = AppProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsIdRoute = AppProjectsIdRouteImport.update({
  id: '/projects/$id',
  path: '/projects/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/$': typeof AppSplatRoute
  '/backlog': typeof AppBacklogRoute
  '/body': typeof AppBodyRoute
  '/calendar': typeof AppCalendarRoute
  '/dashboard': typeof AppDashboardRoute
  '/finances': typeof AppFinancesRoute
  '/goals': typeof AppGoalsRoute
  '/languages': typeof AppLanguagesRoute
  '/reviews': typeof AppReviewsRoute
  '/settings': typeof AppSettingsRoute
  '/notes/$id': typeof AppNotesIdRoute
  '/projects/$id': typeof AppProjectsIdRoute
  '/notes/': typeof AppNotesIndexRoute
  '/projects/': typeof AppProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/$': typeof AppSplatRoute
  '/backlog': typeof AppBacklogRoute
  '/body': typeof AppBodyRoute
  '/calendar': typeof AppCalendarRoute
  '/dashboard': typeof AppDashboardRoute
  '/finances': typeof AppFinancesRoute
  '/goals': typeof AppGoalsRoute
  '/languages': typeof AppLanguagesRoute
  '/reviews': typeof AppReviewsRoute
  '/settings': typeof AppSettingsRoute
  '/notes/$id': typeof AppNotesIdRoute
  '/projects/$id': typeof AppProjectsIdRoute
  '/notes': typeof AppNotesIndexRoute
  '/projects': typeof AppProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/$': typeof AppSplatRoute
  '/_app/backlog': typeof AppBacklogRoute
  '/_app/body': typeof AppBodyRoute
  '/_app/calendar': typeof AppCalendarRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/finances': typeof AppFinancesRoute
  '/_app/goals': typeof AppGoalsRoute
  '/_app/languages': typeof AppLanguagesRoute
  '/_app/reviews': typeof AppReviewsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/notes/$id': typeof AppNotesIdRoute
  '/_app/projects/$id': typeof AppProjectsIdRoute
  '/_app/notes/': typeof AppNotesIndexRoute
  '/_app/projects/': typeof AppProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/$'
    | '/backlog'
    | '/body'
    | '/calendar'
    | '/dashboard'
    | '/finances'
    | '/goals'
    | '/languages'
    | '/reviews'
    | '/settings'
    | '/notes/$id'
    | '/projects/$id'
    | '/notes/'
    | '/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/$'
    | '/backlog'
    | '/body'
    | '/calendar'
    | '/dashboard'
    | '/finances'
    | '/goals'
    | '/languages'
    | '/reviews'
    | '/settings'
    | '/notes/$id'
    | '/projects/$id'
    | '/notes'
    | '/projects'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/$'
    | '/_app/backlog'
    | '/_app/body'
    | '/_app/calendar'
    | '/_app/dashboard'
    | '/_app/finances'
    | '/_app/goals'
    | '/_app/languages'
    | '/_app/reviews'
    | '/_app/settings'
    | '/_app/notes/$id'
    | '/_app/projects/$id'
    | '/_app/notes/'
    | '/_app/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/$': {
      id: '/_app/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof AppSplatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/backlog': {
      id: '/_app/backlog'
      path: '/backlog'
      fullPath: '/backlog'
      preLoaderRoute: typeof AppBacklogRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/body': {
      id: '/_app/body'
      path: '/body'
      fullPath: '/body'
      preLoaderRoute: typeof AppBodyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/calendar': {
      id: '/_app/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/finances': {
      id: '/_app/finances'
      path: '/finances'
      fullPath: '/finances'
      preLoaderRoute: typeof AppFinancesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/goals': {
      id: '/_app/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof AppGoalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/languages': {
      id: '/_app/languages'
      path: '/languages'
      fullPath: '/languages'
      preLoaderRoute: typeof AppLanguagesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reviews': {
      id: '/_app/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof AppReviewsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notes/': {
      id: '/_app/notes/'
      path: '/notes'
      fullPath: '/notes/'
      preLoaderRoute: typeof AppNotesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notes/$id': {
      id: '/_app/notes/$id'
      path: '/notes/$id'
      fullPath: '/notes/$id'
      preLoaderRoute: typeof AppNotesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/': {
      id: '/_app/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AppProjectsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$id': {
      id: '/_app/projects/$id'
      path: '/projects/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof AppProjectsIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppSplatRoute: typeof AppSplatRoute
  AppBacklogRoute: typeof AppBacklogRoute
  AppBodyRoute: typeof AppBodyRoute
  AppCalendarRoute: typeof AppCalendarRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppFinancesRoute: typeof AppFinancesRoute
  AppGoalsRoute: typeof AppGoalsRoute
  AppLanguagesRoute: typeof AppLanguagesRoute
  AppReviewsRoute: typeof AppReviewsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppNotesIdRoute: typeof AppNotesIdRoute
  AppProjectsIdRoute: typeof AppProjectsIdRoute
  AppNotesIndexRoute: typeof AppNotesIndexRoute
  AppProjectsIndexRoute: typeof AppProjectsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppSplatRoute: AppSplatRoute,
  AppBacklogRoute: AppBacklogRoute,
  AppBodyRoute: AppBodyRoute,
  AppCalendarRoute: AppCalendarRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppFinancesRoute: AppFinancesRoute,
  AppGoalsRoute: AppGoalsRoute,
  AppLanguagesRoute: AppLanguagesRoute,
  AppReviewsRoute: AppReviewsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppNotesIdRoute: AppNotesIdRoute,
  AppProjectsIdRoute: AppProjectsIdRoute,
  AppNotesIndexRoute: AppNotesIndexRoute,
  AppProjectsIndexRoute: AppProjectsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
