/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppBodyRouteImport } from './routes/_app/body'
import { Route as AppCalendarRouteImport } from './routes/_app/calendar'
import { Route as AppCareerRouteImport } from './routes/_app/career'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppGoalsRouteImport } from './routes/_app/goals'
import { Route as AppKnowledgeRouteImport } from './routes/_app/knowledge'
import { Route as AppMoneyRouteImport } from './routes/_app/money'
import { Route as AppNotesRouteImport } from './routes/_app/notes'
import { Route as AppPortugueseRouteImport } from './routes/_app/portuguese'
import { Route as AppPrinciplesRouteImport } from './routes/_app/principles'
import { Route as AppProjectsRouteImport } from './routes/_app/projects'
import { Route as AppQuestsRouteImport } from './routes/_app/quests'
import { Route as AppReviewsRouteImport } from './routes/_app/reviews'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppSocialRouteImport } from './routes/_app/social'
import { Route as AppStyleRouteImport } from './routes/_app/style'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppBodyRoute = AppBodyRouteImport.update({
  id: '/body',
  path: '/body',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppCareerRoute = AppCareerRouteImport.update({
  id: '/career',
  path: '/career',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppGoalsRoute = AppGoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => AppRoute,
} as any)
const AppKnowledgeRoute = AppKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => AppRoute,
} as any)
const AppMoneyRoute = AppMoneyRouteImport.update({
  id: '/money',
  path: '/money',
  getParentRoute: () => AppRoute,
} as any)
const AppNotesRoute = AppNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => AppRoute,
} as any)
const AppPortugueseRoute = AppPortugueseRouteImport.update({
  id: '/portuguese',
  path: '/portuguese',
  getParentRoute: () => AppRoute,
} as any)
const AppPrinciplesRoute = AppPrinciplesRouteImport.update({
  id: '/principles',
  path: '/principles',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsRoute = AppProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AppRoute,
} as any)
const AppQuestsRoute = AppQuestsRouteImport.update({
  id: '/quests',
  path: '/quests',
  getParentRoute: () => AppRoute,
} as any)
const AppReviewsRoute = AppReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSocialRoute = AppSocialRouteImport.update({
  id: '/social',
  path: '/social',
  getParentRoute: () => AppRoute,
} as any)
const AppStyleRoute = AppStyleRouteImport.update({
  id: '/style',
  path: '/style',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/body': typeof AppBodyRoute
  '/calendar': typeof AppCalendarRoute
  '/career': typeof AppCareerRoute
  '/dashboard': typeof AppDashboardRoute
  '/goals': typeof AppGoalsRoute
  '/knowledge': typeof AppKnowledgeRoute
  '/money': typeof AppMoneyRoute
  '/notes': typeof AppNotesRoute
  '/portuguese': typeof AppPortugueseRoute
  '/principles': typeof AppPrinciplesRoute
  '/projects': typeof AppProjectsRoute
  '/quests': typeof AppQuestsRoute
  '/reviews': typeof AppReviewsRoute
  '/settings': typeof AppSettingsRoute
  '/social': typeof AppSocialRoute
  '/style': typeof AppStyleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/body': typeof AppBodyRoute
  '/calendar': typeof AppCalendarRoute
  '/career': typeof AppCareerRoute
  '/dashboard': typeof AppDashboardRoute
  '/goals': typeof AppGoalsRoute
  '/knowledge': typeof AppKnowledgeRoute
  '/money': typeof AppMoneyRoute
  '/notes': typeof AppNotesRoute
  '/portuguese': typeof AppPortugueseRoute
  '/principles': typeof AppPrinciplesRoute
  '/projects': typeof AppProjectsRoute
  '/quests': typeof AppQuestsRoute
  '/reviews': typeof AppReviewsRoute
  '/settings': typeof AppSettingsRoute
  '/social': typeof AppSocialRoute
  '/style': typeof AppStyleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/body': typeof AppBodyRoute
  '/_app/calendar': typeof AppCalendarRoute
  '/_app/career': typeof AppCareerRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/goals': typeof AppGoalsRoute
  '/_app/knowledge': typeof AppKnowledgeRoute
  '/_app/money': typeof AppMoneyRoute
  '/_app/notes': typeof AppNotesRoute
  '/_app/portuguese': typeof AppPortugueseRoute
  '/_app/principles': typeof AppPrinciplesRoute
  '/_app/projects': typeof AppProjectsRoute
  '/_app/quests': typeof AppQuestsRoute
  '/_app/reviews': typeof AppReviewsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/social': typeof AppSocialRoute
  '/_app/style': typeof AppStyleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/body'
    | '/calendar'
    | '/career'
    | '/dashboard'
    | '/goals'
    | '/knowledge'
    | '/money'
    | '/notes'
    | '/portuguese'
    | '/principles'
    | '/projects'
    | '/quests'
    | '/reviews'
    | '/settings'
    | '/social'
    | '/style'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/body'
    | '/calendar'
    | '/career'
    | '/dashboard'
    | '/goals'
    | '/knowledge'
    | '/money'
    | '/notes'
    | '/portuguese'
    | '/principles'
    | '/projects'
    | '/quests'
    | '/reviews'
    | '/settings'
    | '/social'
    | '/style'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/body'
    | '/_app/calendar'
    | '/_app/career'
    | '/_app/dashboard'
    | '/_app/goals'
    | '/_app/knowledge'
    | '/_app/money'
    | '/_app/notes'
    | '/_app/portuguese'
    | '/_app/principles'
    | '/_app/projects'
    | '/_app/quests'
    | '/_app/reviews'
    | '/_app/settings'
    | '/_app/social'
    | '/_app/style'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/body': {
      id: '/_app/body'
      path: '/body'
      fullPath: '/body'
      preLoaderRoute: typeof AppBodyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/calendar': {
      id: '/_app/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/career': {
      id: '/_app/career'
      path: '/career'
      fullPath: '/career'
      preLoaderRoute: typeof AppCareerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/goals': {
      id: '/_app/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof AppGoalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/knowledge': {
      id: '/_app/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof AppKnowledgeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/money': {
      id: '/_app/money'
      path: '/money'
      fullPath: '/money'
      preLoaderRoute: typeof AppMoneyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notes': {
      id: '/_app/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof AppNotesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/portuguese': {
      id: '/_app/portuguese'
      path: '/portuguese'
      fullPath: '/portuguese'
      preLoaderRoute: typeof AppPortugueseRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/principles': {
      id: '/_app/principles'
      path: '/principles'
      fullPath: '/principles'
      preLoaderRoute: typeof AppPrinciplesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects': {
      id: '/_app/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AppProjectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/quests': {
      id: '/_app/quests'
      path: '/quests'
      fullPath: '/quests'
      preLoaderRoute: typeof AppQuestsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reviews': {
      id: '/_app/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof AppReviewsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/social': {
      id: '/_app/social'
      path: '/social'
      fullPath: '/social'
      preLoaderRoute: typeof AppSocialRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/style': {
      id: '/_app/style'
      path: '/style'
      fullPath: '/style'
      preLoaderRoute: typeof AppStyleRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppBodyRoute: typeof AppBodyRoute
  AppCalendarRoute: typeof AppCalendarRoute
  AppCareerRoute: typeof AppCareerRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppGoalsRoute: typeof AppGoalsRoute
  AppKnowledgeRoute: typeof AppKnowledgeRoute
  AppMoneyRoute: typeof AppMoneyRoute
  AppNotesRoute: typeof AppNotesRoute
  AppPortugueseRoute: typeof AppPortugueseRoute
  AppPrinciplesRoute: typeof AppPrinciplesRoute
  AppProjectsRoute: typeof AppProjectsRoute
  AppQuestsRoute: typeof AppQuestsRoute
  AppReviewsRoute: typeof AppReviewsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSocialRoute: typeof AppSocialRoute
  AppStyleRoute: typeof AppStyleRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBodyRoute: AppBodyRoute,
  AppCalendarRoute: AppCalendarRoute,
  AppCareerRoute: AppCareerRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppGoalsRoute: AppGoalsRoute,
  AppKnowledgeRoute: AppKnowledgeRoute,
  AppMoneyRoute: AppMoneyRoute,
  AppNotesRoute: AppNotesRoute,
  AppPortugueseRoute: AppPortugueseRoute,
  AppPrinciplesRoute: AppPrinciplesRoute,
  AppProjectsRoute: AppProjectsRoute,
  AppQuestsRoute: AppQuestsRoute,
  AppReviewsRoute: AppReviewsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSocialRoute: AppSocialRoute,
  AppStyleRoute: AppStyleRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
